name: EchoSql
version: '${project.version}'
main: me.fliqq.echosql.EchoSql
api-version: '1.20'
loadbefore:
  - EchoPickaxe
  - EchoMines
  - EchoChat
  - EchoMultiEconomy
  - EchoEssential
  - EchoPrisonRank
  - EchoMenu