package me.fliqq.echomines.enom;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import org.bukkit.Material;

public enum SolidBlocks {
    STONE(Material.STONE),
    COBBLESTONE(Material.COBBLESTONE),
    ANDESITE(Material.ANDESITE),
    GRANITE(Material.GRANITE),
    DIORITE(Material.DIORITE),
    SMOOTH_STONE(Material.SMOOTH_STONE),
    BRICKS(Material.BRICKS),
    STONE_BRICKS(Material.STONE_BRICKS),
    MOSSY_STONE_BRICKS(Material.MOSSY_STONE_BRICKS),
    CRACKED_STONE_BRICKS(Material.CRACKED_STONE_BRICKS),
    CHISELED_STONE_BRICKS(Material.CHISELED_STONE_BRICKS),
    POLISHED_ANDESITE(Material.POLISHED_ANDESITE),
    POLISHED_GRANITE(Material.POLISHED_GRANITE),
    POLISHED_DIORITE(Material.POLISHED_DIORITE),
    CONCRETE_WHITE(Material.WHITE_CONCRETE),
    CONCRETE_ORANGE(Material.ORANGE_CONCRETE),
    CONCRETE_MAGENTA(Material.MAGENTA_CONCRETE),
    CONCRETE_LIGHT_BLUE(Material.LIGHT_BLUE_CONCRETE),
    CONCRETE_YELLOW(Material.YELLOW_CONCRETE),
    CONCRETE_LIME(Material.LIME_CONCRETE),
    CONCRETE_PINK(Material.PINK_CONCRETE),
    CONCRETE_GRAY(Material.GRAY_CONCRETE),
    CONCRETE_LIGHT_GRAY(Material.LIGHT_GRAY_CONCRETE),
    CONCRETE_CYAN(Material.CYAN_CONCRETE),
    CONCRETE_PURPLE(Material.PURPLE_CONCRETE),
    CONCRETE_BLUE(Material.BLUE_CONCRETE),
    CONCRETE_BROWN(Material.BROWN_CONCRETE),
    CONCRETE_GREEN(Material.GREEN_CONCRETE),
    CONCRETE_RED(Material.RED_CONCRETE),
    CONCRETE_BLACK(Material.BLACK_CONCRETE),
    TERRACOTTA(Material.TERRACOTTA),
    WHITE_TERRACOTTA(Material.WHITE_TERRACOTTA),
    ORANGE_TERRACOTTA(Material.ORANGE_TERRACOTTA),
    MAGENTA_TERRACOTTA(Material.MAGENTA_TERRACOTTA),
    LIGHT_BLUE_TERRACOTTA(Material.LIGHT_BLUE_TERRACOTTA),
    YELLOW_TERRACOTTA(Material.YELLOW_TERRACOTTA),
    LIME_TERRACOTTA(Material.LIME_TERRACOTTA),
    PINK_TERRACOTTA(Material.PINK_TERRACOTTA),
    GRAY_TERRACOTTA(Material.GRAY_TERRACOTTA),
    LIGHT_GRAY_TERRACOTTA(Material.LIGHT_GRAY_TERRACOTTA),
    CYAN_TERRACOTTA(Material.CYAN_TERRACOTTA),
    PURPLE_TERRACOTTA(Material.PURPLE_TERRACOTTA),
    BLUE_TERRACOTTA(Material.BLUE_TERRACOTTA),
    BROWN_TERRACOTTA(Material.BROWN_TERRACOTTA),
    GREEN_TERRACOTTA(Material.GREEN_TERRACOTTA),
    RED_TERRACOTTA(Material.RED_TERRACOTTA),
    BLACK_TERRACOTTA(Material.BLACK_TERRACOTTA),
    NETHERRACK(Material.NETHERRACK),
    NETHER_BRICKS(Material.NETHER_BRICKS),
    RED_NETHER_BRICKS(Material.RED_NETHER_BRICKS),
    NETHER_QUARTZ_ORE(Material.NETHER_QUARTZ_ORE),
    NETHER_GOLD_ORE(Material.NETHER_GOLD_ORE),
    BASALT(Material.BASALT),
    POLISHED_BASALT(Material.POLISHED_BASALT),
    BLACKSTONE(Material.BLACKSTONE),
    POLISHED_BLACKSTONE(Material.POLISHED_BLACKSTONE),
    END_STONE(Material.END_STONE),
    END_STONE_BRICKS(Material.END_STONE_BRICKS),
    DIAMOND_BLOCK(Material.DIAMOND_BLOCK),
    EMERALD_BLOCK(Material.EMERALD_BLOCK),
    GOLD_BLOCK(Material.GOLD_BLOCK),
    IRON_BLOCK(Material.IRON_BLOCK),
    COAL_BLOCK(Material.COAL_BLOCK),
    LAPIS_BLOCK(Material.LAPIS_BLOCK),
    QUARTZ_BLOCK(Material.QUARTZ_BLOCK),
    OBSIDIAN(Material.OBSIDIAN),
    NETHERITE_BLOCK(Material.NETHERITE_BLOCK),
    TUFF(Material.TUFF),
    CALCITE(Material.CALCITE),
    DRIPSTONE_BLOCK(Material.DRIPSTONE_BLOCK),
    DEEPSLATE(Material.DEEPSLATE),
    COBBLED_DEEPSLATE(Material.COBBLED_DEEPSLATE),
    POLISHED_DEEPSLATE(Material.POLISHED_DEEPSLATE),
    DEEPSLATE_BRICKS(Material.DEEPSLATE_BRICKS),
    CRACKED_DEEPSLATE_BRICKS(Material.CRACKED_DEEPSLATE_BRICKS),
    CHISELED_DEEPSLATE(Material.CHISELED_DEEPSLATE),
    WHITE_GLAZED_TERRACOTTA(Material.WHITE_GLAZED_TERRACOTTA),
    ORANGE_GLAZED_TERRACOTTA(Material.ORANGE_GLAZED_TERRACOTTA),
    MAGENTA_GLAZED_TERRACOTTA(Material.MAGENTA_GLAZED_TERRACOTTA),
    LIGHT_BLUE_GLAZED_TERRACOTTA(Material.LIGHT_BLUE_GLAZED_TERRACOTTA),
    YELLOW_GLAZED_TERRACOTTA(Material.YELLOW_GLAZED_TERRACOTTA),
    LIME_GLAZED_TERRACOTTA(Material.LIME_GLAZED_TERRACOTTA),
    PINK_GLAZED_TERRACOTTA(Material.PINK_GLAZED_TERRACOTTA),
    GRAY_GLAZED_TERRACOTTA(Material.GRAY_GLAZED_TERRACOTTA),
    LIGHT_GRAY_GLAZED_TERRACOTTA(Material.LIGHT_GRAY_GLAZED_TERRACOTTA),
    CYAN_GLAZED_TERRACOTTA(Material.CYAN_GLAZED_TERRACOTTA),
    PURPLE_GLAZED_TERRACOTTA(Material.PURPLE_GLAZED_TERRACOTTA),
    BLUE_GLAZED_TERRACOTTA(Material.BLUE_GLAZED_TERRACOTTA),
    BROWN_GLAZED_TERRACOTTA(Material.BROWN_GLAZED_TERRACOTTA),
    GREEN_GLAZED_TERRACOTTA(Material.GREEN_GLAZED_TERRACOTTA),
    RED_GLAZED_TERRACOTTA(Material.RED_GLAZED_TERRACOTTA),
    BLACK_GLAZED_TERRACOTTA(Material.BLACK_GLAZED_TERRACOTTA),
    COPPER_BLOCK(Material.COPPER_BLOCK),
    EXPOSED_COPPER(Material.EXPOSED_COPPER),
    WEATHERED_COPPER(Material.WEATHERED_COPPER),
    OXIDIZED_COPPER(Material.OXIDIZED_COPPER),
    CUT_COPPER(Material.CUT_COPPER),
    EXPOSED_CUT_COPPER(Material.EXPOSED_CUT_COPPER),
    WEATHERED_CUT_COPPER(Material.WEATHERED_CUT_COPPER),
    OXIDIZED_CUT_COPPER(Material.OXIDIZED_CUT_COPPER);

    private final Material material;
    private static final List<SolidBlocks> VALUES = Collections.unmodifiableList(Arrays.asList(values()));
    private static final int SIZE = VALUES.size();
    private static final Random RANDOM = new Random();

    SolidBlocks(Material material) {
        this.material = material;
    }

    public Material getMaterial() {
        return material;
    }

    public static SolidBlocks getRandomBlock() {
        return VALUES.get(RANDOM.nextInt(SIZE));
    }
}